config/routes.rb
Rails.application.routes.draw do
  get 'space_ratings/create'
  get 'bookings/create'
  devise_for :users
  root to: "spaces#index"

  resources :spaces, except: :index do
    resources :bookings, only: [:create, :show]
    resources :space_ratings, only: :create
    resources :booking_dates, only: [:new, :create]
  end

  resources :booking_dates, only: :destroy
  resources :bookings, only: :update

  resources :dashboards, only: :index do
    collection do
      get "/infos", to: "dashboards#infos"
      get "/favoris", to: "dashboards#favoris"
      get "/bookings", to: "dashboards#bookings"
      get "/wishspace", to: "dashboards#wishspace"
      get "/wishspace/new", to: "dashboards#new_wishspace"
      post "/wishspace/create", to: "dashboards#create_wishspace"
      get "/owner", to: "dashboards#owner" #reservations des locaux du owner
    end
  end
  resources :messages, only: :create
  get "/search", to: "spaces#results", as: "search_results"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :booking_dates
  has_many :space_ratings, dependent: :destroy
  has_many_attached :photos

  validates :photos, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [:city],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show results]

  # GET /spaces
  def index
    @spaces = Space.all
  end

  def results
    @spaces = Space.all
    if params[:space_profession].present?
      @spaces = @spaces.where(space_profession: params[:space_profession])
    end
    if params[:query].present?
      @spaces = @spaces.search_by_city(params[:query])
    end
    @markers = @spaces.geocoded.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { space: space })
      }
    end
  end

  # GET /spaces/1
  def show
    @booking = Booking.new
    # @booking.booking_dates.build
    @space_rating = SpaceRating.new
    @marker = { lat: @space.latitude, lng: @space.longitude }
    @bookings = @space.bookings
    @booking_date = BookingDate.new
    @selected_days = @space.booking_dates.where(user: current_user).where(booking: nil).pluck(:selected_day).sort.uniq
    @selected_days_collection = @space.booking_dates.where(user: current_user).where(booking: nil).sort.uniq
    @selected_days_disable = @space.booking_dates.where.not(booking: nil).pluck(:selected_day)
    hash_of_periods = count_periods(@selected_days)

    @number_of_months = hash_of_periods[:months]
    @number_of_weeks = hash_of_periods[:weeks]
    @number_of_isolated_days = hash_of_periods[:isolated_days]
    @total_amount = (@number_of_months * @space.price_per_month) + (@number_of_weeks * @space.price_per_week) + (@number_of_isolated_days * @space.price_per_day)
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  def create
    @space = Space.new(space_params)
    @space.user = current_user

    if @space.save
      redirect_to space_path(@space), notice: "Space was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /spaces/1
  def update
    if @space.update(space_params)
      redirect_to @space, notice: "Space was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /spaces/1
  def destroy
    @space.destroy
    redirect_to root_path, notice: "Space was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_space
    @space = Space.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def space_params
    params.require(:space).permit(:city, :address, :space_profession, :description, :price_per_day, :price_per_week, :price_per_month, photos: [])
  end

  def count_periods(dates)
    months_count = 0
    weeks_count = 0
    isolated_days_count = 0

    while dates.any?
      if dates.size >= 30 && (dates[29] - dates[0]).to_i == 29
        months_count += 1
        dates = dates.drop(30)
      elsif dates.size >= 7 && (dates[6] - dates[0]).to_i == 6
        weeks_count += 1
        dates = dates.drop(7)
      else
        isolated_days_count += 1
        dates = dates.drop(1)
      end
    end

    { months: months_count, weeks: weeks_count, isolated_days: isolated_days_count }
  end
end

app/views/spaces/_form.html.erb
<%= simple_form_for(@space) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :city %>
    <%= f.input :address %>
    <%= f.input :space_profession, collection: ['Coiffure', 'Esthétique', 'Barbier', 'Cuisine', 'Salle de réunion'] %>
    <%= f.input :description %>
    <%= f.input :price_per_day %>
    <%= f.input :price_per_week %>
    <%= f.input :price_per_month %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to "Annuler", root_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/spaces/_info_window.html.erb
<div id="popup-window">
  <%= link_to space_path(space) do %>
    <div class="card-map">
      <%= cl_image_tag space.photos.first.key, crop: :fill, class:"listing-img" %>
      <div class="title-map mt-2">
        <strong><%= space.address%></strong>
      </div>
      <div class="map-content d-flex justify-content-between">
        <p>
          <%= space.space_profession %>
        </p>
        <p>
          <strong><%= space.price_per_day %> €/jour</strong>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/spaces/_space.html.erb
<div id="<%= dom_id space %>">

  <div id="carouselExample" class="carousel slide" style="width: 100%; height: 500px;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= cl_image_tag @space.photos.first.key, crop: :fill, style: "width: 100%; height: 500px; object-fit: cover;" %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag @space.photos.second.key, crop: :fill, style: "width: 100%; height: 500px; object-fit: cover;" %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag @space.photos.last.key, crop: :fill, style: "width: 100%; height: 500px; object-fit: cover;" %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/spaces/edit.html.erb
<div class="container">
  <h1>Editing space</h1>

  <%= render "form", space: @space %>

  <br>

  <div>
    <%= link_to "Voir mon espace", @space, class: "btn btn-primary" %> |
    <%= link_to "Retour aux espaces", root_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/spaces/index.html.erb
<div class="container">

  <div class="banner mb-3">
    <div class="container">
      <h1>Trouvez l'espace professionnel <br >
      qu'il vous faut !</h1>
      <div id="search">
        <%= form_with url: search_results_path, method: :get, class: "d-flex" do %>
        <select class="form-select" aria-label="Métier" name="space_profession">
          <option selected label="Métier"></option>
          <option value="Coiffure">Coiffure</option>
          <option value="Esthétique">Esthétique</option>
          <option value="Barbier">Barbier</option>
        </select>
        <%= text_field_tag :query,
          params[:query],
          value: "#{params[:query]}",
          class: "form-control",
          placeholder: "Ville"%>
        <select id="durée" class="form-select" aria-label="Durée" name="Durée">
          <option selected label="Durée"></option>
          <option value="1">Jours</option>
          <option value="2">Semaine</option>
          <option value="3">Mois</option>
        </select>
        <%= submit_tag "Rechercher", name: "Ville", class: "btn btn-primary", id: "rechercher" %>
        <% end %>
      </div>
    </div>
  </div>

  <div id="spaces">
    <% @spaces.each do |space| %>
      <%= link_to space_path(space) do %>
        <div class="card-spaces">
          <%= cl_image_tag space.photos.first.key, crop: :fill, class:"listing-img" %>
          <div class="card-title mt-2">
            <%= space.city %>
          </div>
          <div class="card-content d-flex justify-content-between">
            <p>
              <%= space.space_profession %>
            </p>
            <p>
              <strong><%= space.price_per_day %> €/jour</strong>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="contact">
    <h2>Nous Contacter</h2>
    <form>
      <input type="text" placeholder="Nom">
      <input type="email" placeholder="Email">
      <input type="tel" placeholder="Téléphone">
      <textarea placeholder="Message"></textarea>
      <input type="submit" value="Envoyer">
    </form>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="container">
  <%= link_to "<< Retour aux espaces", root_path, class:"mt-2" %>
  <div class="mt-3">
    <h1>Décrivez nous votre espace</h1>
    <%= render "form", space: @space %>
  </div>
</div>

app/views/spaces/results.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">

<div class="container-result">
  <div class="d-flex flex-row justify-content-between">
    <!-- Partie gauche avec les résultats de recherche -->
    <div id="spaces-result" style="width: 48%;"> <!-- Utilisation de 48% de la largeur pour laisser un petit espace entre les deux éléments -->
      <% @spaces.each do |space| %>
        <%= link_to space_path(space) do %>
          <div class="card-spaces">
            <%= cl_image_tag space.photos.first.key, crop: :fill, class:"listing-img" %>
            <div class="card-title mt-2">
              <strong><%= space.city %></strong>
            </div>
            <div class="card-content d-flex justify-content-between">
              <p>
                <%= space.space_profession %>
              </p>
              <p>
                <strong><%= space.price_per_day %> €/jour</strong>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- Partie droite avec la carte Mapbox -->
    <div id="map" style="width: 50%; height: 665px; border-radius: 8px;"
      data-controller="map-results"
      data-map-results-markers-value="<%= @markers.to_json %>"
      data-map-results-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>


  <div id="contact">
    <h2>Nous Contacter</h2>
    <form>
      <input type="text" placeholder="Nom">
      <input type="email" placeholder="Email">
      <input type="tel" placeholder="Téléphone">
      <textarea placeholder="Message"></textarea>
      <input type="submit" value="Envoyer">
    </form>
  </div>
</div>

app/views/spaces/show.html.erb
<!-- Show d'espace -->
<div class="container">
  <%= link_to "<< Retour aux espaces", search_results_path, class:"mb-2" %>

  <div class="container-space">
    <div class="d-flex justify-content-between align-self-center">
      <div class="adress-show">
        <h1><%= @space.city %></h1>
        <p><%= @space.address %></p>
      </div>
      <div class="adress-show">
        <h1>5 ⭐</h1>
        <p>Voir tous les avis</p>
      </div>
    </div>


    <div class="d-flex flex-row">
      <div class="col-12 col-lg-8 me-5">
        <%= render @space %>
        <div class="mt-4">
          <h3>Métier recherché : <%= @space.space_profession %></h3>
          <p><%= @space.description %></p>
        </div>

        <div style="width: 100%; height: 300px; border-radius: 8px;"
          data-controller="map"
          data-map-marker-value="<%= @marker.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

        <% @space.space_ratings.each do |sr| %>
        <div class="card mt-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= sr.rating %> ⭐</h5>
            <p class="card-text"><%= sr.comment %></p>
          </div>
        </div>
        <% end %>
      </div>


      <div class="container">
        <div class="booking-wrapper text-secondary" data-controller="toggle-calendar">
        <h3>Dates de réservation</h3>
          <div class="form-check mb-2 form-switch d-flex align-items-left">
            <label class="form-check-label me-5" for="flexSwitchCheckDefault">À la journée</label>
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault", data-toggle-calendar-target="button" data-action="click->toggle-calendar#toggle">
            <label class="form-check-label ms-2" for="flexSwitchCheckDefault">Par période</label>
          </div>
          <%= simple_form_for [@space, @booking_date], html: {data: {toggle_calendar_target: "dayCalendar"} } do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <%= f.input :selected_day, as: :string,
                                    required: false,
                                    label: "Choisissez vos jours",
                                    input_html: { class: "datepicker", data: { controller: "datepicker",datepicker_selected_days_value: @selected_days.to_json, datepicker_disable_value: @selected_days_disable.to_json }, style: "display: none;" } %>
            <%= f.button :submit, "Ajouter à votre réservation", class: "btn btn-primary"%>
          <% end %>
          <%= simple_form_for @booking_date, url: space_booking_dates_path(@space, value: "range"), method: :post, html: {data: {toggle_calendar_target: "rangeCalendar"} } do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <%= f.input :selected_day, as: :string,
                                    required: false,
                                    label: "Choisissez votre période",
                                    input_html: { class: "datepicker", data: { controller: "datepicker2", datepicker2_selected_days_value: @selected_days.to_json, datepicker2_disable_value: @selected_days_disable.to_json }, style: "display: none;" } %>
            <%= f.button :submit, "Ajouter à votre réservation", class: "btn btn-primary"%>
          <% end %>
        </div>
        <div class="booking-wrapper text-secondary mt-3">
        <div class="detail-resa">
          <h3> Votre réservation </h3>
        </div>
        <div data-controller="remove-date" data-remove-date-target="list">
          <%= render "shared/list", locals: {selected_days_collection: @selected_days_collection} %>
        </div>
        <div class="detail-resa mt-3">
          <p><strong> Tarifs </strong></p>
          <div class="d-flex justify-content-between">
            <p> Par jour : <%= @space.price_per_day %>€ x <%= @number_of_isolated_days %></p>
            <p> <%= @number_of_isolated_days * @space.price_per_day %>€HT </p>
          </div>
          <div class="d-flex justify-content-between">
            <p> Par semaine : <%= @space.price_per_week %>€ x <%= @number_of_weeks %></p>
            <p> <%= @number_of_weeks * @space.price_per_week %>€HT </p>
          </div>
          <div class="d-flex justify-content-between">
            <p> Par mois : <%= @space.price_per_month %>€ x <%= @number_of_months %></p>
            <p> <%= @number_of_months * @space.price_per_month %>€HT </p>
          </div>
        </div>
        <div class="detail-resa mt-3">
          <p><strong> Détails prix </strong></p>
          <div class="d-flex justify-content-between">
            <p> Total location </p>
            <p> <%= @total_amount %>€HT </p>
          </div>
          <div class="d-flex justify-content-between">
            <p> Frais de service </p>
            <p> <%= (@total_amount * 0.10).to_i %>€HT </p>
          </div>
        </div>
        <div class="detail-resa mt-3">
          <div class="d-flex justify-content-between">
          <p><strong> TOTAL </strong></p>
          <p><strong> <%= (@total_amount + (@total_amount * 0.10)).to_i %>€HT </strong></p>
          </div>
        </div class="mt-3">
          <%= simple_form_for @booking, url: space_bookings_path(@space), method: :post do |form| %>
            <%= form.submit "Valider Ma Commande" , class:"mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

  <div class="container">
    <div id="contact">
      <h3> Laisser un commentaire </h3>
      <%= simple_form_for [@space, @space_rating] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :comment %>
          <%= f.input :rating %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>