config/routes.rb
Rails.application.routes.draw do
  get 'space_ratings/create'
  get 'bookings/create'
  devise_for :users
  root to: "spaces#index"

  resources :spaces, except: :index do
    resources :bookings, only: [:create, :show]
    resources :space_ratings, only: :create
    resources :booking_dates, only: [:new, :create]
  end

  resources :booking_dates, only: :destroy
  resources :bookings, only: :update

  resources :dashboards, only: :index do
    collection do
      get "/infos", to: "dashboards#infos"
      get "/favoris", to: "dashboards#favoris"
      get "/bookings", to: "dashboards#bookings"
      get "/wishspace", to: "dashboards#wishspace"
      get "/wishspace/new", to: "dashboards#new_wishspace"
      post "/wishspace/create", to: "dashboards#create_wishspace"
      get "/owner", to: "dashboards#owner" #reservations des locaux du owner
    end
  end
  resources :messages, only: :create
  get "/search", to: "spaces#results", as: "search_results"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
  has_many :booking_dates, dependent: :destroy
  has_many :messages, dependent: :destroy

  # accepts_nested_attributes_for :booking_dates
  enum :status, { pending: 0, accepted: 1, rejected: 2, archived: 3 }

  def start_at
    booking_dates.order(:selected_day).first
  end

  def end_at
    booking_dates.order(:selected_day).last.selected_day
  end

  def self.archive
    find_each do |booking|
      booking.archived! if booking.end_at < Date.today
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @space = Space.find(params[:space_id])
    total_amount = calculate_total_amount
    @booking = Booking.create(total_amount: total_amount)
    @booking.update(space: @space, user: current_user)

    @booking_dates = @space.booking_dates.where(user: current_user).where(booking: nil)

    @booking_dates.each do |booking_date|
      booking_date.update(booking: @booking)
    end
    flash[:notice] = "Votre réservation a bien été prise en compte"
    redirect_to space_booking_path(@booking.space, @booking)
  end

  def show
    @booking = Booking.find(params[:id])
    @message = Message.new
    @messages = @booking.messages
    @selected_days = @booking.booking_dates.pluck(:selected_day)
    hash_of_periods = count_periods(@selected_days)
    @number_of_months = hash_of_periods[:months]
    @number_of_weeks = hash_of_periods[:weeks]
    @number_of_isolated_days = hash_of_periods[:isolated_days]
  end

  def update
    booking = Booking.find(params[:id])
    if params[:value] == "accepter"
      booking.accepted!
      flash[:notice] = "Votre réservation vient d'être acceptée"
    elsif params[:value] == "refuser"
      booking.rejected!
      flash[:alert] = "Votre réservation vient d'être refusée"
    else
      flash[:alert] = "Il y a eu un problème !"
    end
    redirect_to owner_dashboards_path
  end


  def archive_booking
    Booking.archive
  end


  private

  def booking_params
    params.require(:booking).permit(:total_amount, :status)
  end

  def calculate_total_amount
    dates = @space.booking_dates.where(user: current_user).where(booking: nil).pluck(:selected_day).sort
    months_count = 0
    weeks_count = 0
    isolated_days_count = 0

    while dates.any?
      if dates.size >= 30 && (dates[29] - dates[0]).to_i == 29
        months_count += 1
        dates = dates.drop(30)
      elsif dates.size >= 7 && (dates[6] - dates[0]).to_i == 6
        weeks_count += 1
        dates = dates.drop(7)
      else
        isolated_days_count += 1
        dates = dates.drop(1)
      end
    end

    total_price = (@space.price_per_month * months_count) + (@space.price_per_week * weeks_count) + (@space.price_per_day * isolated_days_count)
    total_price_with_taxes = (total_price + (total_price * 0.10)).to_i
  end

  def count_periods(dates)
    months_count = 0
    weeks_count = 0
    isolated_days_count = 0

    while dates.any?
      if dates.size >= 30 && (dates[29] - dates[0]).to_i == 29
        months_count += 1
        dates = dates.drop(30)
      elsif dates.size >= 7 && (dates[6] - dates[0]).to_i == 6
        weeks_count += 1
        dates = dates.drop(7)
      else
        isolated_days_count += 1
        dates = dates.drop(1)
      end
    end

    { months: months_count, weeks: weeks_count, isolated_days: isolated_days_count }
  end
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/show.html.erb
<!-- Show de booking -->
<div class="container">
  <div class="d-flex flex-row justify-content-between">
    <div class="container-booking-show" style="width: 59%; height: 700px; border-radius: 8px;">
      <div class="booking-wrapper text-secondary mt-2" id="booking">
        <h2>Votre réservation <%= @booking.space.space_profession %></h2>
        <%= cl_image_tag @booking.space.photos.first.key, crop: :fill, class:"booking-img-chat" %>
        <div class="d-flex flex-row justify-content-between">
          <div class="bloc-resa mt-3 mb-3">
            <div class="adresse-resa  mb-4">
              <h4>À partir du <%= @booking.booking_dates.first.selected_day.strftime("%d/%m/%Y") %></h4>
              <h4><%= @booking.space.address %></h4>
            </div>
            <div class="mt-3">
              <p><strong> Durée de location </strong></p>
              <div class="d-flex justify-content-between">
                <p> <%= @number_of_isolated_days %> jours x <%= @booking.space.price_per_day %>€HT</p>
                <p> <%= @number_of_isolated_days * @booking.space.price_per_day %>€HT </p>
              </div>
              <div class="d-flex justify-content-between">
                <p> <%= @number_of_weeks %> semaines x <%= @booking.space.price_per_week %>€HT</p>
                <p> <%= @number_of_weeks * @booking.space.price_per_week %>€HT </p>
              </div>
              <div class="d-flex justify-content-between mb-3">
                <p> <%= @number_of_months %> mois x <%= @booking.space.price_per_month %>€HT </p>
                <p> <%= @number_of_months * @booking.space.price_per_month %>€HT </p>
              </div>
            </div>
            <p><strong> Détails prix </strong></p>
            <div class="d-flex justify-content-between">
              <p> Total location </p>
              <p> <%= @booking.total_amount.to_i %>€HT </p>
            </div>
            <div class="d-flex justify-content-between">
              <p> Frais de service </p>
              <p> <%= (@booking.total_amount * 0.10).to_i %>€HT </p>
            </div>
            <div class="d-flex justify-content-between mt-3">
              <p><strong> TOTAL </strong></p>
              <p><strong> <%= (@booking.total_amount + (@booking.total_amount * 0.10)).to_i %>€HT </strong></p>
            </div>
            <button class="button-voir mt-3" role="button">Télécharger mon reçu</button>
          </div>

          <div class="calendrier mt-5">
            <%= simple_form_for [@booking] do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <%= f.input :status, as: :string,
                                    required: false,
                                    disable: true,
                                    label: "Calendrier des dates réservées",
                                    input_html: { class: "datepicker special-date", data: { controller: "flatshow",  flatshow_selected_days_value: @selected_days.to_json }, style: "display: none;" } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


<!-- Messagerie liée au booking -->
    <div class="container-chatroom-rounded" style="width: 39%; height: 700px; border-radius: 8px;" data-controller="booking-subscription"  data-booking-subscription-booking-id-value="<%= @booking.id %>">
      <div class="chatroom">
        <div class="messages" data-booking-subscription-target="messages">
          <h2>Messagerie</h2>
          <% @booking.messages.each do |message| %>
            <%= render "messages/message", message: message %>
          <% end %>
        </div>
      </div>

      <div class="container-input align-items-center">
        <%= simple_form_for @message, url: messages_path(booking_id: @booking), method: "post",
          html: {data: {action: "turbo:submit-end->booking-subscription#resetForm"}, class: "d-flex"} do |f|%>
          <%= f.input :content,
            label: false,
            wrapper_html: {class: "flex-grow-1 input-wrapper"}
            %>
          <%= f.submit "Envoyer", class: "btn btn-primary send-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>