config/routes.rb
Rails.application.routes.draw do
  get 'space_ratings/create'
  get 'bookings/create'
  devise_for :users
  root to: "spaces#index"

  resources :spaces, except: :index do
    resources :bookings, only: [:create, :show]
    resources :space_ratings, only: :create
    resources :booking_dates, only: [:new, :create]
  end

  resources :booking_dates, only: :destroy
  resources :bookings, only: :update

  resources :dashboards, only: :index do
    collection do
      get "/infos", to: "dashboards#infos"
      get "/favoris", to: "dashboards#favoris"
      get "/bookings", to: "dashboards#bookings"
      get "/wishspace", to: "dashboards#wishspace"
      get "/wishspace/new", to: "dashboards#new_wishspace"
      post "/wishspace/create", to: "dashboards#create_wishspace"
      get "/owner", to: "dashboards#owner" #reservations des locaux du owner
    end
  end
  resources :messages, only: :create
  get "/search", to: "spaces#results", as: "search_results"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 align-items-center" id="border">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block text-success">
      <span>Suivez-nous sur nos réseaux sociaux </span>
    </div>
    <!-- Left -->
    <!-- Right -->
    <div>
      <a href="https://www.instagram.com/quoopen/" class="me-4 reseaux" target="_blank">
        <i class="fab fa-instagram fa-2x"></i>
      </a>
      <a href="https://www.linkedin.com/company/quoopen.com/" class="me-4 reseaux" target="_blank">
        <i class="fab fa-linkedin fa-2x"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="fw-bold mb-4 text-success">
            La presse en parle
          </h6>
          <div class="d-flex">
            <div class="logo-container me-4">
              <a href="https://preproduction.admin.quoopen.com/pdf/start.pdf" target="_blank">
                <%= image_tag("Start.png", alt: "logo", width: 100) %>
              </a>
            </div>
            <div class="logo-container me-4">
              <a href="https://www.forbes.fr/mediasfrance/quoopen/" target="_blank">
                <%= image_tag("forbes.png", alt: "logo", width:100) %>
              </a>
            </div>
            <div class="logo-container me-4" id="forbes">
              <a href="https://admin.quoopen.com/pdf/tribune.pdf" target="_blank">
                <%= image_tag("Tribune.png", alt: "logo", id: "tribune", width:135) %>
              </a>
            </div>
          </div>
        </div>
        <!-- Grid column -->
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="fw-bold mb-4 text-success">
           À propos
          </h6>
          <p>
            <a href="#!" class="text-light">CGU</a>
          </p>
          <p style="white-space: nowrap;">
            <a href="#!" class="text-light">Politique de confidentialité</a>
          </p>
          <p>
            <a href="#!" class="text-light">Mentions légales</a>
          </p>
        </div>
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->
  <!-- Copyright -->
  <div class="text-align-left p-2 text-light" style="background-color: rgba(0, 0, 0, 0.05);">
    <p>© 2024 Copyright Space-Ease</p>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_list.html.erb
<div class="detail-resa mt-3">
  <p><strong> Dates à réserver </strong></p>
  <% @selected_days_collection.each do |day| %>
    <div class="d-flex justify-content-between">
      <p>Le <%= day.selected_day.strftime("%d" + "/" + "%m" + "/" + "%Y") %></p>
      <%= link_to booking_date_path(day), class: "remove-date-link", remote: true, data: { turbo_method: false, confirm: "Are you sure?", remove_date_target:"link", action: "click->remove-date#remove" }  do %>
        <i class="fa-solid fa-xmark" style="color: #69F701;"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom border-success border-2">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo-container ml-2">
      <%= image_tag("Logo-Space-Ease.png", alt: "logo", class: "navbar-logo") %>
    </div>
  <% end %>
  <!-- Métier dropdown -->
      <% unless request.path == root_path %>
        <%= render partial: "shared/search" %>
      <% end %>
        <!-- bouton profil navbar -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <button type="button" class="btn btn-outline-primary"><%= link_to "Nouvel espace", new_space_path, class: "new" %></button>
          <li class="nav-item dropdown">
            <a href="#" class="avatar ms-1" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
            </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Tableau de bord", dashboards_path, class: "dropdown-item" %>
            <%= link_to "Réservations", bookings_dashboards_path, class: "dropdown-item" %>
            <%= link_to "Favoris", favoris_dashboards_path, class: "dropdown-item" %>
            <%= link_to "Gérer mes annonces", owner_dashboards_path, class: "dropdown-item" %>
            <%= link_to "Profil", infos_dashboards_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
          </li>
        <% else %>
        <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa-regular fa-user avatar fa-2x" style="color: #69F701;"></i>          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown", id="connexion">
            <%= link_to "Connexion/Inscription", new_user_session_path, class: "dropdown-item" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
  <div>
      <%= form_with url: search_results_path, method: :get, class: "d-flex" do %>
      <select class="form-select" aria-label="Métier" name="space_profession">
        <option selected label="Profession"></option>
        <option value="Coiffure">Coiffure</option>
        <option value="Esthétique">Esthétique</option>
        <option value="Barbier">Barbier</option>
      </select>
      <%= text_field_tag :query,
        params[:query],
        value: "#{params[:query]}",
        class: "form-control",
        placeholder: "Ville"%>
      <select id="durée" class="form-select" aria-label="Durée" name="durée">
        <option selected label="Durée"></option>
        <option value="1">Jours</option>
        <option value="2">Semaine</option>
        <option value="3">Mois</option>
      </select>
      <%= submit_tag "Rechercher", name: "Ville", class: "btn btn-primary", id: "rechercher" %>
    <% end %>
  </div>