config/routes.rb
Rails.application.routes.draw do
  get 'space_ratings/create'
  get 'bookings/create'
  devise_for :users
  root to: "spaces#index"

  resources :spaces, except: :index do
    resources :bookings, only: [:create, :show]
    resources :space_ratings, only: :create
    resources :booking_dates, only: [:new, :create]
  end

  resources :booking_dates, only: :destroy
  resources :bookings, only: :update

  resources :dashboards, only: :index do
    collection do
      get "/infos", to: "dashboards#infos"
      get "/favoris", to: "dashboards#favoris"
      get "/bookings", to: "dashboards#bookings"
      get "/wishspace", to: "dashboards#wishspace"
      get "/wishspace/new", to: "dashboards#new_wishspace"
      post "/wishspace/create", to: "dashboards#create_wishspace"
      get "/owner", to: "dashboards#owner" #reservations des locaux du owner
    end
  end
  resources :messages, only: :create
  get "/search", to: "spaces#results", as: "search_results"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end

  def infos
  end

  def bookings
  end

  def favoris
  end

  def new_wishspace
    @space = Space.new
  end

  def create_wishspace
    @space = Space.new
  end

  def wishspace
  end

  def owner
    @owner_bookings = Booking.joins(:space).where(spaces: { user: current_user})
    @sorted_bookings = @owner_bookings.sort_by { |booking| booking.start_at }
    @pendings = @owner_bookings.where(status: "pending")
    @accepted = @owner_bookings.where(status: "accepted")
    @rejected = @owner_bookings.where(status: "rejected")
    @archived = @owner_bookings.where(status: "archived")
  end

  private

  def set_user
    @user = current_user
  end

  def space_params
  end
end

app/views/dashboards/_form.html.erb
<%= simple_form_for(@space) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :city %>
    <%= f.input :address %>
    <%= f.input :space_profession, collection: ['Coiffure', 'Esthétique', 'Barbier', 'Cuisine', 'Salle de réunion'] %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to "Annuler", root_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/dashboards/bookings.html.erb
<div class="container">
  <div class="space-title mt-3">
    <h2>Mes réservations</h2>
  </div>
  <div class="row">
    <% current_user.bookings.each do |booking| %>
      <div id="booking-card-link" class="col-lg-4 col-md-6 col-sm-12">
          <div class="booking-wrapper mt-3 booking">
            <%= link_to space_booking_path(booking.space, booking) do %>
            <h4><%= booking.space.city %> • <%= booking.space.space_profession %> </h4>
            <%= cl_image_tag booking.space.photos.first.key, crop: :fill, class:"booking-img" %>
            <div class="detail-resa">
              <p><strong><%= booking.space.address %></strong></p>
              <p>À partir du <%= booking.booking_dates.first.selected_day.strftime("%d/%m/%Y") %></p>
            </div>
            <div class="d-flex justify-content-between mt-2 text-gray">
              <p> TOTAL réservation </p>
              <p><strong> <%= booking.total_amount.to_i %>€HT </strong></p>
            </div>
            <div class="d-flex justify-content-between">
              <button class="button-4" role="button"><%= booking.status %></button>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/favoris.html.erb
<h1>Favoris</h1>

<%= link_to "Retour au tableau de bord", dashboards_path %>

app/views/dashboards/index.html.erb
<h1>Dashboard</h1>

<ul>
  <li> <%= link_to "Infos", infos_dashboards_path %></li>
  <li> <%= link_to "Réservations", bookings_dashboards_path %></li>
  <li> <%= link_to "Favoris", favoris_dashboards_path %></li>
  <li> <%= link_to "Vous avez repéré un lieu ?", wishspace_dashboards_path %></li>
  <li> <%= link_to "Espace propriétaire", owner_dashboards_path %></li>
</ul>

app/views/dashboards/infos.html.erb
<div class="container">
  <h1>Mes informations personnelles</h1>


  <h5>Prénom:</h5>
  <%= current_user.first_name %><br ><br >

  <h5>Nom:</h5>
  <%= current_user.last_name %><br ><br >

  <h5>Email:</h5>
  <%= current_user.email %><br ><br >

  <h5>Numéro de téléphone:</h5>
  <%= current_user.phone_number %><br ><br >

  <h5>Adresse:</h5>
  <%= current_user.address %><br ><br >

  <h5>Code postal:</h5>
  <%= current_user.postal_code %><br ><br >

  <h5>Profession:</h5>
  <%= current_user.user_profession %><br ><br >

  <h5>Entreprise:</h5>
  <%= current_user.company_name %><br ><br >

  <h5>N° siret:</h5>
  <%= current_user.siret_number %><br ><br >

  <%= link_to "Retour au tableau de bord", dashboards_path %>
</div>

app/views/dashboards/new_wishspace.html.erb
<h1>Vous avez trouvé un lieu ?</h1>

<%= render "form", space: @space%>

<%= link_to "Retour au tableau de bord", dashboards_path %>

app/views/dashboards/owner.html.erb
<div class="container">
  <h2>Gestion des réservations</h2>

  <div class="container-space">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">À valider</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">À venir</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Terminées</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-rejected-tab" data-bs-toggle="pill" data-bs-target="#pills-rejected" type="button" role="tab" aria-controls="pills-rejected" aria-selected="false">Refusées</button>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <table class="full-width-table">
          <tr class="table-header">
            <th scope="col">Accepter</th>
            <th scope="col">Refuser</th>
            <th scope="col">À partir du</th>
            <th scope="col">Freelance</th>
            <th scope="col">Nbre de jours</th>
            <th scope="col">Versement total</th>
            <th scope="col">Détails</th>
          </tr>
          <% @pendings.each do |booking| %>
            <tr class="table-row">
              <td>
                <%= simple_form_for booking, url: booking_path(booking, value: "accepter"), method: :patch do |form| %>
                  <button type="submit" class="custom-button">
                    <i class="fa-solid fa-circle-check"></i>
                  </button>
                <% end %>
              </td>
              <td>
                <%= simple_form_for booking, url: booking_path(booking, value: "refuser"), method: :patch do |form| %>
                  <button type="submit" class="reject-button">
                    <i class="fa-solid fa-circle-xmark"></i>
                  </button>
                <% end %>
              </td>
              <td><%= booking.booking_dates.first.selected_day.strftime("%d/%m/%Y") %></td>
              <td><%= booking.user.company_name %></td>
              <td><%= booking.booking_dates.count %></td>
              <td><%= booking.total_amount.to_i %>€HT</td>
              <td><%= link_to space_booking_path(booking.space, booking) do %>
                    <i class="fa-solid fa-circle-plus"></i>
                  <% end %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <table class="full-width-table">
          <tr class="table-header">
            <th scope="col">À partir du</th>
            <th scope="col">Freelance</th>
            <th scope="col">Nbre de jours</th>
            <th scope="col">Versement total</th>
            <th scope="col">Détails</th>
            <th scope="col">Annuler</th>
          </tr>
          <% @accepted.each do |booking| %>
          <tr class="table-row">
            <td><%= booking.booking_dates.first.selected_day.strftime("%d/%m/%Y") %></td>
            <td><%= booking.user.company_name %></td>
            <td><%= booking.booking_dates.count %></td>
            <td><%= booking.total_amount.to_i %>€HT</td>
            <td><%= link_to space_booking_path(booking.space, booking) do %>
                  <i class="fa-solid fa-circle-plus"></i>
                <% end %></td>
            <td><% unless booking.rejected? %>
              <%= simple_form_for booking, url: booking_path(booking, value: "refuser"), method: :patch do |form| %>
              <button type="submit" class="reject-button">
                <i class="fa-solid fa-circle-xmark"></i>
              </button>
              <% end %>
            <% end %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
        <table class="full-width-table">
          <tr class="table-header">
            <th scope="col">À partir du</th>
            <th scope="col">Freelance</th>
            <th scope="col">Nbre de jours</th>
            <th scope="col">Versement total</th>
            <th scope="col">Détails</th>
          </tr>
          <% @archived.each do |booking| %>
          <tr class="table-row">
            <td><%= booking.booking_dates.first.selected_day.strftime("%d/%m/%Y") %></td>
            <td><%= booking.user.company_name %></td>
            <td><%= booking.booking_dates.count %></td>
            <td><%= booking.total_amount.to_i %>€HT</td>
            <td><%= link_to space_booking_path(booking.space, booking) do %>
                  <i class="fa-solid fa-circle-plus"></i>
                <% end %></td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="tab-pane fade" id="pills-rejected" role="tabpanel" aria-labelledby="pills-rejected-tab">
        <table class="full-width-table">
          <tr class="table-header">
            <th scope="col">À partir du</th>
            <th scope="col">Freelance</th>
            <th scope="col">Nbre de jours</th>
            <th scope="col">Versement total</th>
            <th scope="col">Détails</th>
            <th scope="col">Accepter</th>
          </tr>
          <% @rejected.each do |booking| %>
          <tr class="table-row">
            <td><%= booking.booking_dates.first.selected_day.strftime("%d/%m/%Y") %></td>
            <td><%= booking.user.company_name %></td>
            <td><%= booking.booking_dates.count %></td>
            <td><%= booking.total_amount.to_i %>€HT</td>
            <td><%= link_to space_booking_path(booking.space, booking) do %>
                  <i class="fa-solid fa-circle-plus"></i>
                <% end %>
            </td>
            <td><% unless booking.accepted? %>
                <%= simple_form_for booking, url: booking_path(booking, value: "accepter"), method: :patch do |form| %>
                  <button type="submit" class="custom-button">
                    <i class="fa-solid fa-circle-check"></i>
                  </button>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <h2 class="mt-4">Mes Espaces</h2>
   <div class="row">
    <% current_user.spaces.each do |owner_space| %>
    <div id="booking-card-link"class="col-lg-3 col-md-6 col-sm-12 booking">
      <%= link_to space_path(owner_space, @space) do %>
        <div class="booking-wrapper text-secondary mt-3" id="espaces">
          <h4><%= owner_space.city %> • <%= owner_space.space_profession %> </h4>
          <%= cl_image_tag owner_space.photos.first.key, crop: :fill, class:"booking-img" %>
          <p><%= owner_space.address %></p>
          <div class="d-flex justify-content-between mt-2">
            <%= link_to "Modifier", edit_space_path(owner_space), class:"btn btn-outline-dark" %>
            <%= link_to "Effacer", space_path(owner_space), class: "btn btn-outline-danger", remote: true, data: { turbo_confirm: "Êtes vous sur ?", turbo_method: :delete } %>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/dashboards/wishspace.html.erb
<h1>Vous avez trouvé un lieu ?</h1>

<%= link_to "New wishspace", wishspace_new_dashboards_path %>

<%= link_to "Retour au tableau de bord", dashboards_path %>